//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneDirectory.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternShipProjectEntitiesOne : DbContext
    {
        public InternShipProjectEntitiesOne()
            : base("name=InternShipProjectEntitiesOne")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Working> Working { get; set; }
    }
}
