//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelephoneDirectory.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working
    {
        public int WorkingId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Administrator { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Administrator Administrator1 { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
